name = "test-discuss"
compatibility_date = "2024-09-27"
workers_dev = false

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "prod"
database_id = "24f36833-9890-493d-ab34-7549fc414340"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "R2"
bucket_name = "assets"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
